name: 'Build'

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          depth: 1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
          cache-dependency-path: go.sum

      - name: build
        run: |
          CGO_ENABLED=0 go build -o app

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app